### ISSUE TITLE
arm65 support

### ISSUE THREAD

**Issue by yjshen324** [yjshen324/test#1]
windows and linux

**Comment by yjshen324** [comment]
grome and kde

**Comment by yjshen324** [comment]
usa and china

**Comment by yjshen324** [comment]
japan and english

**Comment by yjshen324** [comment]
india and russia

**Comment by yjshen324** [comment]
sigapore

**Comment by yjshen324** [comment]
germany

**Comment by yjshen324** [comment]
austria

**Comment by yjshen324** [comment]
@robinshine test availability

**Comment by robinshine** [comment]
See you have quotation here.

On Feb 15, 2023, at 20:03, yjshen324 ***@***.***> wrote:



@robinshine<https://github.com/robinshine> test availability
